import React from 'react';

const HowAiverse = () => {
  return (
    <div className="aiversebg" id="about" style={{ position: 'relative' }}>
      <div className="howToFilter"></div>
      <div className="top-header">
        <h1 className="header-aiverse">How do StarkAI-Art NFTs work?</h1>
        <p
          className="p1"
          style={{
            fontFamily:
              '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif',
          }}
        >
          StarkAI-Art nft are minted from images generated by two ai models
          working in sync. They are based on one of the biggest models ever
          trained in Russia.
          {/* <br /> */}
          These nfts signify ownership and access to a no. of features coming in
          future
        </p>
      </div>
      <img
        src="https://github.com/Gautambnsl/aiverse-nft/blob/main/final-frontend/src/assets/images/logo4.png?raw=true"
        className="techImg"
      />
      <div style={{ position: 'absolute', bottom: '0', marginLeft: '12%' }}>
        <img
          src="https://github.com/Gautambnsl/aiverse-nft/blob/main/final-frontend/src/assets/images/robot3.png?raw=true"
          className="robot"
        />
        <div className="box">
          <h3 className="imagin">Imaginate to Create</h3>
        </div>
      </div>
    </div>
  );
};

export default HowAiverse;
